language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: d6lwArYthUoHrZmCKdahaJcIWmyAuNZd+4mTzHhsNCiWF3J6pAA9KnuaXsZ4TBHs9ZAO/kzBP1a0py5W3hey5zJELgosc+Do1V/P7CFLfnr29xJSR+HGaY2t/YXGsboIPkK3Kp5XWzuVOjmQk/hkvcDsKlXHo9atWluZxFKqZ0Fom0VRM8V2bGlsH8niyFHiiLdQnSe9Ky2CxS6BgFW8t4KShdj7pzEpSxtLYpFRSKV7NCPynlfK5x1uSjHBM2DBBI0mHSIT7q5f7f2cxNh00USjBZ8GaEOIpgVKW3afyvsPbESVxYir5UUsIAoPYxK07hsdF8OHAOkH+dziIip22HU/fuMAI0sA2duDEVKDjOSlGMaR2tW0xKQ8A22Arh4a5hJzR3K54TlWNoDPd1AQyZLnHuigStKFx+hkhqbH0GUC6lH8AetyrhFEEYKw/NQCnfG88IFTETmlElkQkzdOMuwH2k6sBYzfpr2gjU3GCeFN7oWgx0Oj71T6BlzbfZKmfi50KTPUeuFSCblPDBNZ4ZLNYWrCPihhuPQSpUsxQ2f47j32yW9hrR1cEkMkME6z4liJRtUy07FcNVFqPU6Ua90g6RTKi6rjWVG0aXsRmFVCtj3N2BZ+L/EDgK6pPriy/yYRJkW40D9Tfka9LZmqc2NElSuSZ8QqNZl77g2BXeg=
  app: agile-hamlet-96595
  on:
    repo: Laurn17/seedsonal-capstone
